# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(650, 509)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(30, 30, 621, 381))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget_fiteo = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_fiteo.setObjectName("tabWidget_fiteo")
        self.tab_modelo = QtWidgets.QWidget()
        self.tab_modelo.setObjectName("tab_modelo")
        self.label_cdc = QtWidgets.QLabel(self.tab_modelo)
        self.label_cdc.setGeometry(QtCore.QRect(10, 10, 57, 15))
        self.label_cdc.setObjectName("label_cdc")
        self.plainTextEdit_cdc = QtWidgets.QPlainTextEdit(self.tab_modelo)
        self.plainTextEdit_cdc.setGeometry(QtCore.QRect(60, 10, 191, 21))
        self.plainTextEdit_cdc.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_cdc.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_cdc.setObjectName("plainTextEdit_cdc")
        self.widget = QtWidgets.QWidget(self.tab_modelo)
        self.widget.setGeometry(QtCore.QRect(10, 40, 335, 17))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_parametros = QtWidgets.QLabel(self.widget)
        self.label_parametros.setObjectName("label_parametros")
        self.horizontalLayout.addWidget(self.label_parametros)
        self.label_fijar = QtWidgets.QLabel(self.widget)
        self.label_fijar.setObjectName("label_fijar")
        self.horizontalLayout.addWidget(self.label_fijar)
        self.label_limiteinferior = QtWidgets.QLabel(self.widget)
        self.label_limiteinferior.setObjectName("label_limiteinferior")
        self.horizontalLayout.addWidget(self.label_limiteinferior)
        self.label_limitesuperior = QtWidgets.QLabel(self.widget)
        self.label_limitesuperior.setObjectName("label_limitesuperior")
        self.horizontalLayout.addWidget(self.label_limitesuperior)
        self.label_ajuste = QtWidgets.QLabel(self.widget)
        self.label_ajuste.setObjectName("label_ajuste")
        self.horizontalLayout.addWidget(self.label_ajuste)
        self.tabWidget_fiteo.addTab(self.tab_modelo, "")
        self.tab_ajuste = QtWidgets.QWidget()
        self.tab_ajuste.setObjectName("tab_ajuste")
        self.label_metodoajuste = QtWidgets.QLabel(self.tab_ajuste)
        self.label_metodoajuste.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_metodoajuste.setObjectName("label_metodoajuste")
        self.label_ponderacion = QtWidgets.QLabel(self.tab_ajuste)
        self.label_ponderacion.setGeometry(QtCore.QRect(160, 10, 121, 16))
        self.label_ponderacion.setObjectName("label_ponderacion")
        self.tabWidget_fiteo.addTab(self.tab_ajuste, "")
        self.tab_simulacion = QtWidgets.QWidget()
        self.tab_simulacion.setObjectName("tab_simulacion")
        self.tabWidget_fiteo.addTab(self.tab_simulacion, "")
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_bode = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_bode.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_bode.setObjectName("verticalLayout_bode")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.splitter_2)
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_nyquist = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_nyquist.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_nyquist.setObjectName("verticalLayout_nyquist")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 20))
        self.menubar.setObjectName("menubar")
        self.menu_Archivo = QtWidgets.QMenu(self.menubar)
        self.menu_Archivo.setObjectName("menu_Archivo")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionImportar = QtWidgets.QAction(MainWindow)
        self.actionImportar.setObjectName("actionImportar")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.actionAbrir)
        self.menu_Archivo.addAction(self.actionImportar)
        self.menu_Archivo.addAction(self.actionGuardar)
        self.menu_Archivo.addSeparator()
        self.menu_Archivo.addAction(self.actionExit)
        self.menubar.addAction(self.menu_Archivo.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_fiteo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_cdc.setText(_translate("MainWindow", "CDC:"))
        self.label_parametros.setText(_translate("MainWindow", "Parámetros"))
        self.label_fijar.setText(_translate("MainWindow", "Fijar"))
        self.label_limiteinferior.setText(_translate("MainWindow", "Límite Inferior"))
        self.label_limitesuperior.setText(_translate("MainWindow", "Límite Superior"))
        self.label_ajuste.setText(_translate("MainWindow", "Ajuste"))
        self.tabWidget_fiteo.setTabText(self.tabWidget_fiteo.indexOf(self.tab_modelo), _translate("MainWindow", "Modelo"))
        self.label_metodoajuste.setText(_translate("MainWindow", "Método de ajuste"))
        self.label_ponderacion.setText(_translate("MainWindow", "Ponderación"))
        self.tabWidget_fiteo.setTabText(self.tabWidget_fiteo.indexOf(self.tab_ajuste), _translate("MainWindow", "Ajuste"))
        self.tabWidget_fiteo.setTabText(self.tabWidget_fiteo.indexOf(self.tab_simulacion), _translate("MainWindow", "Simulación"))
        self.menu_Archivo.setTitle(_translate("MainWindow", "&Archivo"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionImportar.setText(_translate("MainWindow", "Importar"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionExit.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

